-- This file is none script-generated and should  be manually edited. 
-- Localizers may copy this file to edit as necessary. 

local AceLocale = LibStub:GetLibrary("AceLocale-3.0") 
local L = AceLocale:NewLocale("SexyCooldown", "ruRU", true) 
if not L then return end 

 
-- ./core.lua
L["Select an options sub-category to get started."] = "Выберите подкатегорию опций, чтобы начать"
L["Bars"] = "Бары"
L["Create new bar"] = "Создать новый бар"
L["Profiles"] = "Профили"
L["Reset to defaults"] = "Восстановить"
L["Reset all colors in this group to the icon defaults"] = ["Сбросить все цвета в этой группе на значения по умолчанию для значков"

-- ./loadstub.lua
-- no localization

-- ./Modules/Auras.lua
L["All buffs on me"] = "Все баффы на мне"
L["Show the duration of buffs on me on this bar"] = "Показывает длительность баффов на мне на этой панели"
L["All debuffs on me"] = "Все дебаффы на мне"
L["Show the duration of my debuffs on me on this bar"] = "Показывает длительность моих дебаффов на мне на этой панели"
L["My buffs on me"] = "Мои баффы на мне"
L["Show the duration of my buffs on me on this bar"] = "Показывает продолжительность действия моих баффов на этой панели"
L["My debuffs on me"] = "Мои дебаффы на мне"
L["Show the duration of debuffs on me on this bar"] = "Показывать длительность дебаффов на мне на этой панели"
L["My focus buffs"] = "Мои бафы фокуса"
L["Show the duration of my buffs on my focus on this bar"] = "Показывает длительность баффов по фокусу на этой панели"
L["My focus debuffs"] = "Мои дебафы фокуса"
L["Show the duration of my debuffs on my focus on this bar"] = "Показывает длительность дебаффов по фокусу на этой панели"
L["My target buffs"] = "Мои целевые баффы"
L["Show the duration of my buffs on my target on this bar"] = "Показает продолжительность действия моих баффов на моей цели на этой панели"
L["My target debuffs"] = "Мои целевые дебаффы"
L["Show the duration of my debuffs on my target on this bar"] = "Показывает длительность моих дебаффов на моей цели на этой панели"
L["All target buffs"] = "Все целевые баффы"
L["Show the duration of all buffs on my target on this bar"] = "Показывает длительность всех баффов на моей цели на этой панели"
L["All target debuffs"] =["Все целевые дебаффы"
L["Show the duration of all debuffs on my target on this bar"] = "Показывает длительность всех дебаффов на моей цели на этой панели"

-- ./Modules/Items.lua
L["Items"] = "Предметы"
L["Show my item cooldowns on this bar"] = "Показывать время восстановления моих предметов на этой панели"
L["Internal cooldowns"] = "Внутренние кулдауны"
L["Show internal cooldowns for my items and enchants on this bar."] = "Показывать внутренние кулдауны для моих предметов и чар на этой панели."

-- ./Modules/RaidDebuffs.lua
L["Major Armor Debuff"] = " Ослабление брони"
L["Attack Speed Debuff"] = "Снижение скорости атаки"
L["Bleed Damage"] = "Кровотечение"
L["Cast Speed Debuff"] = "Снижение скорости сотворения чар"
L["Healing Debuff"] = "Исцеляющий дебафф"
L["Physical Damage Reduction"] = "Снижение физического урона"
L["Physical Vulnerability"] = "Физическая уязвимость"
L["Spell Crit Chance"] = "Шанс критического удара заклинанием"
L["Spell Damage Taken"] = "Полученный урон от заклинаний"
L["Major Armor Debuffs"] = "Ослабления брони"
L["Show the duration of major armor debuffs on the target"] = "Показать длительность основных дебаффов брони на цели"
L["Attack Speed Debuffs"] = "Снижение скорости атаки"
L["Show the duration of attack speed debuffs on the target"] = "Показывать длительность дебаффов скорости атаки на цели"
L["Bleed Damage Debuffs"] = "Кровотечение дебафы"
L["Show the duration of bleed damage debuffs on the target"] = "Показать длительность дебаффов кровотечения на цели"
L["Cast Speed Debuffs"] = "Ослабления скорости сотворения чар"
L["Show the duration of cast speed debuffs on the target"] = "Показать продолжительность дебаффов скорости каста на цели"
L["Show the duration of -healing debuffs on the target"] = "Покажзать длительность дебаффов исцеления на цели."
L["Physical Damage Reduction Debuffs"] = "Ослабления снижения физического урона"
L["Show the duration of physical damage reduction debuffs on the target"] = "Показать длительность дебаффов снижения физического урона на цели"
L["Physical Vulnerability Debuffs"] = "Ослабления физической уязвимости"
L["Show the duration of physical vulnerability debuffs on the target"] = "Показать продолжительность дебаффов физической уязвимости на цели"
L["Spell Crit Debuffs"] = "Ослабления критического урона заклинаниями"
L["Show the duration of spell crit chance debuffs on the target"] = "Показывать длительность дебаффов шанса критического удара заклинания на цели"
L["Spell Damage Debuffs"] = "Ослабления урона от заклинаний"
L["Show the duration of spell damage debuffs on the target"] = "Показать длительность дебаффов урона заклинаниями на цели"

-- ./Modules/Spells.lua
L["My spells"] = "Мои заклинания"
L["Show my spell cooldowns on this bar"] = " Показывать мои заклинания на панели"
L["Pet spells"] = "Заклинания питомца"
L["Show my pet's cooldowns on this bar"] = " Показывать заклинания питомца на панели"
L["Show internal cooldowns for my spells and talents on this bar."] = "Показать внутренние кулдауны для моих заклинаний и талантов на этой панели"

-- ./Modules/Totems.lua
L["Totem durations"] = "Продолжительность тотемов"
L["Show my totem durations on this bar"] = "Показать продолжительность действия моих тотемов на этой панели"

-- ./options.lua
L["No outline"] = "Без внешней линии"
L["Outline"] = "Внешняя линия"
L["Thick Outline"] = "Жирная внешняя линия"
L["Left to Right"] = "С лева на право"
L["Right to Left"] = "С права на лево"
L["Top to Bottom"] = "Сверху вниз"
L["Bottom to top"] = "Снизу вверх"
L["Center left"] = "С центра влево"
L["Center right"] = "С центра вправо"
L["Center"] = "Центр"
L["Top left"] = "Вверху слево"
L["Top right"] = "Вверху справо"
L["Top center"] = "Вверху посередине"
L["Bottom left"] = "Снизу слево"
L["Bottom center"] = "Снизу посередине"
L["Bottom right"] = "Снизу справо"
L["Clone from..."] = "Клонировать из"
L["Clone from another bar"] = "Клонировать из другого бара"
L["Icons"] = "Иконки"
L["Right-click an icon on a cooldown bar to blacklist it and prevent it from showing in the future. To remove a cooldown from a blacklist, choose the cooldown to remove from this list."] = "Щелкните правой кнопкой мыши значок на полосе восстановления, чтобы внести его в черный список и предотвратить его отображение в будущем. Чтобы удалить время восстановления из черного списка, выберите время восстановления, которое нужно удалить из этого списка"
L["Blacklist"] = "Черный список"
L["Select an item to remove it from the blacklist."] = "Выберите элемент, чтобы удалить его из черного списка."
L["Removed %s from the SexyCooldown blacklist"] = "%s удален из черного списка SexyCooldown "
L["Clamp to screen"] = "Прижимать к экрану"
L["Prevent icons from running off the screen"] = "Предотвратить исчезновение значков с экрана"
L["Cooldown Text"] = "Текст восстановления"
L["Show Cooldown Text"] = "Показать текст восстановления"
L["Show Stacks"] = "Показать стаки"
L["Show the number of stacks of a buff or debuff"] = "Показать количество стаков баффа или дебаффа"
L["Time corner"] = "Временной угол"
L["Select the corner to anchor the time text to."] = "Выберите угол, к которому нужно привязать текст времени"
L["Stacks corner"] = "Угол стеки"
L["Select the corner to anchor the stack text to."] = "Выберите угол, к которому нужно привязать текст стаков."
L["Stacks offset"] = "Смещение стаков"
L["Offset for stack text"] = "Смещение для текста стаков"
L["Time offset"] = "Смещение времени"
L["Offset for time text"] = "Смещение для времени"
L["Font"] = "Шрифт"
L["Font size"] = "Размер шрифта"
L["Font color"] = "Цвет шрифта"
L["Font Outline"] = "Внешняя линия шрифта"
L["Borders"] = "Границы"
L["Border"] = "Граница"
L["Border color"] = "Цвет границы"
L["Border size"] = "Размер границы"
L["Border inset"] = "Вставка границы"
L["General options"] = "Общие настройки"
L["Icon size"] = "Размер значка"
L["How big to make icons, relative to their parent bar"] = "Насколько большими должны быть значки относительно их родительской панели"
L["Finish Behavior"] = "Поведение при откате"
L["Splash scale"] = "Масштаб всплеска"
L["How big (or small) icons will 'splash' when their cooldown is done"] = "Насколько большие (или маленькие) значки будут« всплескивать », когда их время восстановления истечет"
L["Splash speed"] = "Скорость всплеска"
L["How quickly to play the splash animation once a cooldown is done"] = "Как быстро воспроизвести анимацию всплеска после перезарядки"
L["Disable tooltips"] = "Отключить всплывающие подсказки"
L["Don't show item or spell tooltips when you hover over their icons on the bar."] = "Не показывать подсказки к предметам или заклинаниям при наведении курсора на их значки на панели"
L["Disable mouse"] = "Отключить мышь"
L["Don't allow mouse interaction with icons. If you turn this off, you won't be able to blacklist items."] = "Не позволяет мыши взаимодействовать со значками. Если вы отключите это, вы не сможете заносить элементы в черный список"
L["Pulse speed"] = "Скорость импульса"
L["Speed to pulse overlapping icons"] = "Скорость, чтобы пульсировать перекрывающиеся значки"
L["Bar"] = "Бар"
L["General Options"] = "Общие настройки"
L["Name"] = "Имя"
L["A descriptive name for this bar"] = "Описательное название для этой панели"
L["Lock"] = "Заблокировать"
L["Lock this bar to prevent resizing or moving"] = "Заблокируйте эту панель, чтобы предотвратить изменение размера или перемещение"
L["Flexible"] = "Гибкий"
L["Collapse the bar to the length of your longest active cooldown."] = "Расстягивает бар на время вашего наибольшего активного восстановления"
L["Advanced Options"] = "Расширенные опции"
L["Enable advanced configuration options"] = "Включить дополнительные параметры конфигурации"
L["Bar Orientation"] = "Ориентация бара"
L["Bar and icon direction."] = "Бар и значок направления"
L["Time and Duration settings"] = "Настройки времени и продолжительности"
L["Time Compression"] = "Сжатие времени"
L["Time display scaling factor"] = "Коэффициент масштабирования отображения времени"
L["Max Time"] = "Максимальное время"
L["Max time to display, in seconds"] = "Максимальное время отображения в секундах"
L["Minimum duration"] = "Минимальная продолжительность"
L["Cooldowns shorter than this will not be shown."] = "Время восстановления короче этого значения отображаться не будет "
L["Maximum duration"] = "Максимальная продолжительность"
L["Cooldowns longer than this will not be shown. Set to 0 to show all cooldowns."] = "Время восстановления, превышающее это, отображаться не будет. Установите значение 0, чтобы отобразить все время восстановления"
L["Border and Background"] = "Граница и фон"
L["Background"] = "Фон"
L["Background color"] = "Цвет фона"
L["Border insets"] = "Вставка границы"
L["Position and Size"] = "Положение и размер"
L["Height"] = "Высота"
L["Width"] = "Длина"
L["Horizontal Position"] = "Горизонтальная позиция"
L["Horizontal offset from screen center"] = "Смещение по горизонтали от центра экрана"
L["Vertical Offset"] = "Вертикальное смещение"
L["Vertical offset from screen center"] = "Смещение по вертикали от центра экрана"
L["Inactive Opacity"] = "Неактивная непрозрачность"
L["Opacity to set the bar to when a cooldown is not active"] = "Непрозрачность, чтобы установить полосу, когда перезарядка неактивна "
L["Show Splash Anchor"] = "Показать якорь"
L["Show an anchor that you can use to move the splash anchor, which controls where icons 'splash' when they are cooled down."] = "Показать якорь, который можно использовать для перемещения якоря-заставки, который определяет, где значки« всплывают », когда они восстанавливаются"
L["Reset Splash Anchor"] = "Сбросить якорь"
L["Reset splash anchor to its default position."] = "Сбросить якорь  в положение по умолчанию"
L["/!\\ Delete This Bar /!\\"] = "/!\\ Удалить этот Bar /!\\"
L["Permanently delete this bar."] = "Удалить эту панель навсегда"
L["Are you sure you want to delete this bar?"] = "Вы уверены, что хотите удалить эту панель?"
L["Custom timings"] = "Пользовательские тайминги"
L["Specify a comma-delimited list of intervals to mark on the bar, in seconds. For example: 1,5,10,30,45,60,180"] = "Задайте список интервалов в секундах, разделенных запятыми, которые нужно отметить на шкале. Например: 1,5,10,30,45,60,180"
L["Timings format"] = "Формат времени"
L["Select the display format for timings"] = "Выберите формат отображения времени"
L["Event Types"] = "Типы событий"
L["Event Colors"] = "Цвета событий"

-- ./prototype.lua
-- no localization