-- This file is script-generated and should not be manually edited. 
-- Localizers may copy this file to edit as necessary. 
local AceLocale = LibStub:GetLibrary("AceLocale-3.0") 
local L = AceLocale:NewLocale("SexyCooldown", "zhCN", false) 
if not L then return end 
 
-- ./core.lua
L["Select an options sub-category to get started."] = "从选择一个分类别选项开始。"
L["Bars"] = "计时条"
L["Create new bar"] = "新建计时条"
L["Profiles"] = "配置文件"
L["Reset to defaults"] = "重置为默认"
L["Reset all colors in this group to the icon defaults"] = "重置图标默认组中的所有颜色"

-- ./loadstub.lua
-- no localization

-- ./Modules/Auras.lua
L["All buffs on me"] = "所有我的增益"
L["Show the duration of buffs on me on this bar"] = "在这个计时条上显示我的持续增益"
L["All debuffs on me"] = "所有我的减益"
L["Show the duration of my debuffs on me on this bar"] = "在这个计时条上显示我的持续减益"
L["My buffs on me"] = "所有自身增益"
L["Show the duration of my buffs on me on this bar"] = "在这个计时条上显示自身的持续增益"
L["My debuffs on me"] = "所有自身减益"
L["Show the duration of debuffs on me on this bar"] = "在这个计时条上显示自身的持续减益"
L["My focus buffs"] = "我的焦点增益"
L["Show the duration of my buffs on my focus on this bar"] = "在这个计时条上显示我施放给焦点的持续增益"
L["My focus debuffs"] = "我的焦点目标减益"
L["Show the duration of my debuffs on my focus on this bar"] = "在这个计时条上显示我施放给焦点的持续减益"
L["My target buffs"] = "我的目标增益"
L["Show the duration of my buffs on my target on this bar"] = "在这个计时条上显示我施放给目标的持续增益"
L["My target debuffs"] = "我的目标减益"
L["Show the duration of my debuffs on my target on this bar"] = "在这个计时条上显示我施放给目标的持续减益"
L["All target buffs"] = "所有目标增益"
L["Show the duration of all buffs on my target on this bar"] = "在这个计时条上显示我施放给所有目标的持续增益"
L["All target debuffs"] = "所有目标减益"
L["Show the duration of all debuffs on my target on this bar"] = "在这个计时条上显示我施放给所有目标的持续减益"

-- ./Modules/Items.lua
L["Items"] = "物品"
L["Show my item cooldowns on this bar"] = "在这个计时条上显示我的物品冷却"
L["Internal cooldowns"] = "内置冷却"
L["Show internal cooldowns for my items and enchants on this bar."] = "在这个计时条上显示我的物品和附魔的内置冷却。"

-- ./Modules/RaidDebuffs.lua
L["Bleed"] = "流血类减益"
L["Major Armor"] = "护甲特效类减益"
L["Spell Hit"] = "法术命中类减益"
L["Bleeds on Target"] = "目标的流血类减益"
L["Show the duration of bleeds on the target"] = "显示目标的持续流血类别减益"
L["Major Armor Debuffs"] = "护甲特效类减益"
L["Show the duration of major armor debuffs on the target"] = "显示目标的持续护甲特效类别减益"
L["Spell Hit Debuffs"] = "法术命中类减益"
L["Show the duration of +spell hit debuffs on the target"] = "显示目标的持续增加法术命中类别减益"

-- ./Modules/Spells.lua
L["My spells"] = "我的法术"
L["Show my spell cooldowns on this bar"] = "在这个计时条上显示我的法术冷却"
L["Pet spells"] = "宠物法术"
L["Show my pet's cooldowns on this bar"] = "在这个计时条上显示我的宠物的冷却"
L["Show internal cooldowns for my spells and talents on this bar."] = "在这个计时条上显示我的法术和天赋的内置冷却。"

-- ./Modules/Totems.lua
L["Totem durations"] = "图腾持续"
L["Show my totem durations on this bar"] = "在这个计时条上显示我的图腾持续"

-- ./options.lua
L["No outline"] = "无轮廓"
L["Outline"] = "轮廓"
L["Thick Outline"] = "粗轮廓"
L["Left to Right"] = "从左至右"
L["Right to Left"] = "从右至左"
L["Top to Bottom"] = "从上到下"
L["Bottom to top"] = "从下到上"
L["Center left"] = "中间偏左"
L["Center right"] = "中间偏右"
L["Center"] = "中间"
L["Top left"] = "顶部偏左"
L["Top right"] = "顶部偏右"
L["Top center"] = "顶部中间"
L["Bottom left"] = "底部偏左"
L["Bottom center"] = "底部中间"
L["Bottom right"] = "底部偏右"
L["Clone from..."] = "从…复制"
L["Clone from another bar"] = "从其他计时条复制"
L["Icons"] = "图标"
L["Right-click an icon on a cooldown bar to blacklist it and prevent it from showing in the future. To remove a cooldown from a blacklist, choose the cooldown to remove from this list."] = "右击冷却计时条上的图标添加到黑名单并以后不会再被显示。在黑名单中移除被已过滤的冷却。"
L["Blacklist"] = "黑名单"
L["Select an item to remove it from the blacklist."] = "选择一个物品从黑名单中移除。"
L["Removed %s from the SexyCooldown blacklist"] = "%s已从 SexyCooldown 黑名单中移除"
L["Clamp to screen"] = "置于屏幕内"
L["Prevent icons from running off the screen"] = "防止图标跑到屏幕之外"
L["Cooldown Text"] = "冷却文字"
L["Show Cooldown Text"] = "显示冷却文字"
L["Show Stacks"] = "显示堆叠"
L["Show the number of stacks of a buff or debuff"] = "显示增益或减益的堆叠数字"
L["Time corner"] = "时间位置"
L["Select the corner to anchor the time text to."] = "选择时间文字的角落锚点位置。"
L["Stacks corner"] = "堆叠位置"
L["Select the corner to anchor the stack text to."] = "选择堆叠文字的角落锚点位置。"
L["Stacks offset"] = "堆叠偏移量"
L["Offset for stack text"] = "堆叠文字的偏移量"
L["Time offset"] = "时间偏移量"
L["Offset for time text"] = "时间文字的偏移量"
L["Font"] = "字体"
L["Font size"] = "字体尺寸"
L["Font color"] = "字体颜色"
L["Font Outline"] = "字体轮廓"
L["Borders"] = "边框"
L["Border"] = "边框"
L["Border color"] = "边框颜色"
L["Border size"] = "边框大小"
L["Border inset"] = "边框插入"
L["General options"] = "一般选项"
L["Icon size"] = "图标大小"
L["How big to make icons, relative to their parent bar"] = "相对于计时条设置图标大小。"
L["Finish Behavior"] = "结束行为"
L["Splash scale"] = "闪屏缩放"
L["How big (or small) icons will 'splash' when their cooldown is done"] = "当冷却结束时“闪屏”图标的大小"
L["Splash speed"] = "闪屏速度"
L["How quickly to play the splash animation once a cooldown is done"] = "当冷却结束时播放闪屏动画效果的速度"
L["Disable tooltips"] = "禁用提示"
L["Don't show item or spell tooltips when you hover over their icons on the bar."] = "当鼠标悬停在计时条的图标上时不显示物品或法术提示。"
L["Disable mouse"] = "禁用鼠标"
L["Don't allow mouse interaction with icons. If you turn this off, you won't be able to blacklist items."] = "不允许鼠标与图标互动化。如果启用此选项将不能黑名单物品。"
L["Pulse speed"] = "脉动速度"
L["Speed to pulse overlapping icons"] = "图标重叠脉动速度"
L["Bar"] = "计时条"
L["General Options"] = "一般选项"
L["Name"] = "名称"
L["A descriptive name for this bar"] = "这个计时条的描述性名称"
L["Lock"] = "锁定"
L["Lock this bar to prevent resizing or moving"] = "锁定计时条禁止移动和缩放"
L["Flexible"] = "自适应"
L["Collapse the bar to the length of your longest active cooldown."] = "以最长有效冷却来决定计时条长短。"
L["Advanced Options"] = "高级选项"
L["Enable advanced configuration options"] = "启用高级配置选项"
L["Bar Orientation"] = "计时条定位"
L["Bar and icon direction."] = "计时条和图标位置"
L["Time and Duration settings"] = "时间和持续设置"
L["Time Compression"] = "时间缩写"
L["Time display scaling factor"] = "时间缩写条件"
L["Max Time"] = "最长时间"
L["Max time to display, in seconds"] = "显示的最长时间，秒"
L["Minimum duration"] = "最短持续"
L["Cooldowns shorter than this will not be shown."] = "少于这个的冷却将不被显示。"
L["Maximum duration"] = "最长持续"
L["Cooldowns longer than this will not be shown. Set to 0 to show all cooldowns."] = "大于这个的冷却将不会被被显示。设为0显示所有冷却。"
L["Border and Background"] = "边框和背景"
L["Background"] = "背景"
L["Background color"] = "背景颜色"
L["Border insets"] = "背景插入"
L["Position and Size"] = "位置和大小"
L["Height"] = "高度"
L["Width"] = "宽度"
L["Horizontal Position"] = "水平位置"
L["Horizontal offset from screen center"] = "屏幕中间的水平偏移量"
L["Vertical Offset"] = "垂直偏移量"
L["Vertical offset from screen center"] = "屏幕中间的垂直偏移量"
L["Inactive Opacity"] = "无效不透明度"
L["Opacity to set the bar to when a cooldown is not active"] = "计时条冷却没有启用时的不透明度"
L["Show Splash Anchor"] = "显示闪屏锚点"
L["Show an anchor that you can use to move the splash anchor, which controls where icons 'splash' when they are cooled down."] = "显示可以移动闪屏的锚点，使冷却时“闪屏图标”出现。"
L["Reset Splash Anchor"] = "重置闪屏锚点"
L["Reset splash anchor to its default position."] = "重置闪屏锚点到默认位置。"
L["/!\\ Delete This Bar /!\\"] = "/！\\ 删除此计时条 /！\\"
L["Permanently delete this bar."] = "永久删除此计时条。"
L["Are you sure you want to delete this bar?"] = "确定是否删除此计时条？"
L["Custom timings"] = "自定义计时"
L["Specify a comma-delimited list of intervals to mark on the bar, in seconds. For example: 1,5,10,30,45,60,180"] = "在计时条指定逗号分隔的列表的时间间隔，在几秒钟内。例如：1,5,10,30,45,60,180"
L["Timings format"] = "计时格式"
L["Select the display format for timings"] = "选择显示计时格式"
L["Event Types"] = "事件类别"
L["Event Colors"] = "事件颜色"

-- ./prototype.lua
-- no localization

