-- This file is script-generated and should not be manually edited. 
-- Localizers may copy this file to edit as necessary. 
local AceLocale = LibStub:GetLibrary("AceLocale-3.0") 
local L = AceLocale:NewLocale("SexyCooldown", "zhTW", false) 
if not L then return end 
 
-- ./core.lua
L["Select an options sub-category to get started."] = "從選擇一個分類別選項開始。"
L["Bars"] = "計時條"
L["Create new bar"] = "新建計時條"
L["Profiles"] = "配置文件"
L["Reset to defaults"] = "重置為預設"
L["Reset all colors in this group to the icon defaults"] = "重置圖示預設組中的所有顏色"

-- ./loadstub.lua
-- no localization

-- ./Modules/Auras.lua
L["All buffs on me"] = "所有我的增益"
L["Show the duration of buffs on me on this bar"] = "在這個計時條上顯示我的持續增益"
L["All debuffs on me"] = "所有我的減益"
L["Show the duration of my debuffs on me on this bar"] = "在這個計時條上顯示我的持續減益"
L["My buffs on me"] = "所有自身增益"
L["Show the duration of my buffs on me on this bar"] = "在這個計時條上顯示自身的持續增益"
L["My debuffs on me"] = "所有自身減益"
L["Show the duration of debuffs on me on this bar"] = "在這個計時條上顯示自身的持續減益"
L["My focus buffs"] = "我的焦點增益"
L["Show the duration of my buffs on my focus on this bar"] = "在這個計時條上顯示我施放給焦點的持續增益"
L["My focus debuffs"] = "我的焦點目標減益"
L["Show the duration of my debuffs on my focus on this bar"] = "在這個計時條上顯示我施放給焦點的持續減益"
L["My target buffs"] = "我的目標增益"
L["Show the duration of my buffs on my target on this bar"] = "在這個計時條上顯示我施放給目標的持續增益"
L["My target debuffs"] = "我的目標減益"
L["Show the duration of my debuffs on my target on this bar"] = "在這個計時條上顯示我施放給目標的持續減益"
L["All target buffs"] = "所有目標增益"
L["Show the duration of all buffs on my target on this bar"] = "在這個計時條上顯示我施放給所有目標的持續增益"
L["All target debuffs"] = "所有目標減益"
L["Show the duration of all debuffs on my target on this bar"] = "在這個計時條上顯示我施放給所有目標的持續減益"

-- ./Modules/Items.lua
L["Items"] = "物品"
L["Show my item cooldowns on this bar"] = "在這個計時條上顯示我的物品冷卻"
L["Internal cooldowns"] = "內置冷卻"
L["Show internal cooldowns for my items and enchants on this bar."] = "在這個計時條上顯示我的物品和附魔的內置冷卻。"

-- ./Modules/RaidDebuffs.lua
L["Bleed"] = "流血類減益"
L["Major Armor"] = "護甲特效類減益"
L["Spell Hit"] = "法術命中類減益"
L["Bleeds on Target"] = "目標的流血類減益"
L["Show the duration of bleeds on the target"] = "顯示目標的持續流血類別減益"
L["Major Armor Debuffs"] = "護甲特效類減益"
L["Show the duration of major armor debuffs on the target"] = "顯示目標的持續護甲特效類別減益"
L["Spell Hit Debuffs"] = "法術命中類減益"
L["Show the duration of +spell hit debuffs on the target"] = "顯示目標的持續增加法術命中類別減益"

-- ./Modules/Spells.lua
L["My spells"] = "我的法術"
L["Show my spell cooldowns on this bar"] = "在這個計時條上顯示我的法術冷卻"
L["Pet spells"] = "寵物法術"
L["Show my pet's cooldowns on this bar"] = "在這個計時條上顯示我的寵物的冷卻"
L["Show internal cooldowns for my spells and talents on this bar."] = "在這個計時條上顯示我的法術和天賦的內置冷卻。"

-- ./Modules/Totems.lua
L["Totem durations"] = "圖騰持續"
L["Show my totem durations on this bar"] = "在這個計時條上顯示我的圖騰持續"

-- ./options.lua
L["No outline"] = "無輪廓"
L["Outline"] = "輪廓"
L["Thick Outline"] = "粗輪廓"
L["Left to Right"] = "從左至右"
L["Right to Left"] = "從右至左"
L["Top to Bottom"] = "從上到下"
L["Bottom to top"] = "從下到上"
L["Center left"] = "中間偏左"
L["Center right"] = "中間偏右"
L["Center"] = "中間"
L["Top left"] = "頂部偏左"
L["Top right"] = "頂部偏右"
L["Top center"] = "頂部中間"
L["Bottom left"] = "底部偏左"
L["Bottom center"] = "底部中間"
L["Bottom right"] = "底部偏右"
L["Clone from..."] = "從…複製"
L["Clone from another bar"] = "從其他計時條複製"
L["Icons"] = "圖示"
L["Right-click an icon on a cooldown bar to blacklist it and prevent it from showing in the future. To remove a cooldown from a blacklist, choose the cooldown to remove from this list."] = "右擊冷卻計時條上的圖示添加到黑名單並以后不會再被顯示。在黑名單中移除已被過濾的冷卻。"
L["Blacklist"] = "黑名單"
L["Select an item to remove it from the blacklist."] = "選擇一個物品從黑名單中移除。"
L["Removed %s from the SexyCooldown blacklist"] = "%s已從 SexyCooldown 黑名單中移除"
L["Clamp to screen"] = "置於螢幕內"
L["Prevent icons from running off the screen"] = "防止圖示跑到螢幕之外"
L["Cooldown Text"] = "冷卻文字"
L["Show Cooldown Text"] = "顯示冷卻文字"
L["Show Stacks"] = "顯示堆疊"
L["Show the number of stacks of a buff or debuff"] = "顯示增益或減益的堆疊數字"
L["Time corner"] = "時間位置"
L["Select the corner to anchor the time text to."] = "選擇時間文字的角落錨點位置。"
L["Stacks corner"] = "堆疊位置"
L["Select the corner to anchor the stack text to."] = "選擇堆疊文字的角落錨點位置。"
L["Stacks offset"] = "堆疊偏移量"
L["Offset for stack text"] = "堆疊文字的偏移量"
L["Time offset"] = "時間偏移量"
L["Offset for time text"] = "時間文字的偏移量"
L["Font"] = "字型"
L["Font size"] = "字型尺寸"
L["Font color"] = "字型顏色"
L["Font Outline"] = "字型輪廓"
L["Borders"] = "邊框"
L["Border"] = "邊框"
L["Border color"] = "邊框顏色"
L["Border size"] = "邊框大小"
L["Border inset"] = "邊框插入"
L["General options"] = "一般選項"
L["Icon size"] = "圖示大小"
L["How big to make icons, relative to their parent bar"] = "相對於計時條設置圖示大小。"
L["Finish Behavior"] = "結束行為"
L["Splash scale"] = "閃屏縮放"
L["How big (or small) icons will 'splash' when their cooldown is done"] = "當冷卻結束時“閃屏”圖示的大小"
L["Splash speed"] = "閃屏速度"
L["How quickly to play the splash animation once a cooldown is done"] = "當冷卻結束時播放閃屏動畫效果的速度"
L["Disable tooltips"] = "禁用提示"
L["Don't show item or spell tooltips when you hover over their icons on the bar."] = "當滑鼠懸停在計時條的圖示上時不顯示物品或法術提示。"
L["Disable mouse"] = "禁用滑鼠"
L["Don't allow mouse interaction with icons. If you turn this off, you won't be able to blacklist items."] = "不允許滑鼠與圖示互動化。如果啟用此選項將不能黑名單物品。"
L["Pulse speed"] = "脈動速度"
L["Speed to pulse overlapping icons"] = "圖示重疊脈動速度"
L["Bar"] = "計時條"
L["General Options"] = "一般選項"
L["Name"] = "名稱"
L["A descriptive name for this bar"] = "這個計時條的描述性名稱"
L["Lock"] = "鎖定"
L["Lock this bar to prevent resizing or moving"] = "鎖定計時條禁止移動和縮放"
L["Flexible"] = "自適應"
L["Collapse the bar to the length of your longest active cooldown."] = "以最長有效冷卻來決定計時條長短。"
L["Advanced Options"] = "進階選項"
L["Enable advanced configuration options"] = "啟用進階配置選項"
L["Bar Orientation"] = "計時條定位"
L["Bar and icon direction."] = "計時條和圖示位置"
L["Time and Duration settings"] = "時間和持續設置"
L["Time Compression"] = "時間縮寫"
L["Time display scaling factor"] = "時間縮寫條件"
L["Max Time"] = "最長時間"
L["Max time to display, in seconds"] = "顯示的最長時間，秒"
L["Minimum duration"] = "最短持續"
L["Cooldowns shorter than this will not be shown."] = "少於這個的冷卻將不被顯示。"
L["Maximum duration"] = "最長持續"
L["Cooldowns longer than this will not be shown. Set to 0 to show all cooldowns."] = "大於這個的冷卻將不會被被顯示。設為0顯示所有冷卻。"
L["Border and Background"] = "邊框和背景"
L["Background"] = "背景"
L["Background color"] = "背景顏色"
L["Border insets"] = "背景插入"
L["Position and Size"] = "位置和大小"
L["Height"] = "高度"
L["Width"] = "寬度"
L["Horizontal Position"] = "水平位置"
L["Horizontal offset from screen center"] = "螢幕中間的水平偏移量"
L["Vertical Offset"] = "垂直偏移量"
L["Vertical offset from screen center"] = "螢幕中間的垂直偏移量"
L["Inactive Opacity"] = "無效不透明度"
L["Opacity to set the bar to when a cooldown is not active"] = "計時條冷卻沒有啟用時的不透明度"
L["Show Splash Anchor"] = "顯示閃屏錨點"
L["Show an anchor that you can use to move the splash anchor, which controls where icons 'splash' when they are cooled down."] = "顯示可以移動閃屏的錨點，使冷卻時“閃屏圖示”出現。"
L["Reset Splash Anchor"] = "重置閃屏錨點"
L["Reset splash anchor to its default position."] = "重置閃屏錨點到預設位置。"
L["/!\\ Delete This Bar /!\\"] = "/！\\ 刪除此計時條/！\\"
L["Permanently delete this bar."] = "永久刪除此計時條。"
L["Are you sure you want to delete this bar?"] = "確定是否刪除此計時條？"
L["Custom timings"] = "自訂計時"
L["Specify a comma-delimited list of intervals to mark on the bar, in seconds. For example: 1,5,10,30,45,60,180"] = "在計時條指定逗號分隔的列表的時間間隔，在幾秒鐘內。例如：1,5,10,30,45,60,180"
L["Timings format"] = "計時格式"
L["Select the display format for timings"] = "選擇顯示計時格式"
L["Event Types"] = "事件類別"
L["Event Colors"] = "事件顏色"

-- ./prototype.lua
-- no localization

